
### Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount)
from customer
group by gender

### Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer 
where purchase_amount>= (select avg(purchase_amount) from customer)
and discount_applied = 'Yes'

### Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric), 2) as "average product rating" 
from customer 
group by 1
order by 2 desc
limit 5

### Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select round(avg(purchase_amount), 2) avg_purchase_amount, shipping_type from customer
where shipping_type ='Standard' or shipping_type= 'Express'
group by 2

### Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(*) as total_customers,
round(avg(purchase_amount), 2) as avg_apend, sum(purchase_amount) as total_revenue
from customer
group by 1

### Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

### Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select count(*) as count_of_customers,
case
	when previous_purchases='1' then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as segment
from customer
group by segment

### Q8. What are the top 3 most purchased products within each category? 
with summary as(select category, item_purchased, count(*) as quantity from customer 
group by 1, 2 
order by 1)
select * from (select *, dense_rank() over(partition by category order by quantity desc) as rn from summary)
where rn  <= 3

### Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(*) count_of_customers, subscription_status
from customer 
where previous_purchases>5
group by 2

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as revenue_contribution
from customer 
group by 1

